name: serverless-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Unit testing
        run: npm test

      - name: Deploy to WS
        uses: serverless/github-action@master
        with:
          args: deploy --stage prd --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}